server:
    port: 8080
spring:
    application:
        name: spring-cloud-config-server
cloud:
    config:
        server:
            git:
                uri: https://github.com/GongXudong/PD     # 配置git仓库的地址
                search-paths: conf                        # git仓库地址下的相对地址，可以配置多个，用,分割。
                username: gongxudong                      # git仓库的账号
                password: gong8216885                     # git仓库的密码
